@baseURL = http://localhost:5000/api/articles
@articleID = 5fbed71f3e8e012348c016eb


### GET ALL ARTICLES
GET {{baseURL}}/ HTTP/1.1


### GET AN ARTICLE BY ID
GET {{baseURL}}/{{articleID}}/ HTTP/1.1


### CREATE AN ARTICLE
POST {{baseURL}}/ HTTP/1.1
Content-Type: application/json

{
  "title": "My 1st Article",
  "body": "1st Article Body"
}


### UPDATE AN ARTICLE BY ID
PATCH {{baseURL}}/{{articleID}}/ HTTP/1.1
Content-Type: application/json

{
  "body": "My Updated Article Body"
}


### DELETE AN ARTICLE BY ID
DELETE {{baseURL}}/{{articleID}}/ HTTP/1.1
