@baseURL = http://localhost:5000/api/rants
@rantID = 5fc6b54583161b2e10265c7e


### GET ALL RANTS
GET {{baseURL}}/ HTTP/1.1


### GET A RANT BY ID
GET {{baseURL}}/{{rantID}}/ HTTP/1.1


### CREATE A NEW RANT
POST {{baseURL}}/ HTTP/1.1
Content-Type: application/json

{
  "title": "My 2nd Rant",
  "body": "2nd Rant Body"
}


### UPDATE A RANT BY ID
PATCH {{baseURL}}/{{rantID}}/ HTTP/1.1
Content-Type: application/json

{
  "body": "My Updated Rant Body"
}


### DELETE A RANT BY ID
DELETE {{baseURL}}/{{rantID}}/ HTTP/1.1
